services:
  - type: web
    name: the-beast-fitness-gym
    env: node
    region: singapore
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm run start
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: gym-postgres
          property: connectionString
      - key: NODE_ENV
        value: production

databases:
  - name: gym-postgres
    plan: free
    region: singapore
